name: GITHUB Action
## main 브랜치로 push될떄 아래 workflow 실행
on:
  push:
    branches:
      - main
## main 브랜치로 push될떄 아래 workflow 실행

jobs:
  depoly:
    runs-on: ubuntu-latest
    ## step: 특정 작업을 수행하는 가장 작은 단위
    #JOB은 여런 STEP으로 구성되어 있음
    steps:
      - name: depoly
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # EC2의 주소
          username: ${{ secrets.USERNAME }} # EC2 접속 username
          key: ${{ secrets.PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            sudo su
            git config --global --add safe.directory /var/back-end/financial-board-server
            cd /var/back-end/financial-board-server
            sudo chown -R $USER:$USER .
            sudo chmod -R 755 .
            git pull
            yarn
            yarn build
            yarn typeorm:run-master-data-migration:default
            pm2 kill
            pm2 start dist/main.js --name "backend-server"
