name: GITHUB Action
## main 브랜치로 push될떄 아래 workflow 실행
on:
  push:
    branches:
      - main
## main 브랜치로 push될떄 아래 workflow 실행

jobs:
  ##job 식별하기 위한 id
  deploy-on-test:
    ## ubuntu 환경:최신버전
    runs-on: ubuntu-latest
    ## step: 특정 작업을 수행하는 가장 작은 단위
    #JOB은 여런 STEP으로 구성되어 있음
    steps:
      ## run은 리눅스 명렁 코드
      - name: 테스트
        run: echo "Test Complete"

      - name: 여러 명렁어 쓰기
        run: echo "명렁어 추가"
        ## 깃허브 지금 커밋된 아이디
      - name: 깃 허브 저장된 변수
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - name: 깃 허브 저장된 변수
        run: |
          echo ${{secrets.MY_NAME}}
          echo ${{secrets.MY_HABBIT}}
