name: GITHUB Action

on:
  push:
    branches:
      - main

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
      - name: depoly
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # EC2의 주소
          username: ${{ secrets.USERNAME }} # EC2 접속 username
          key: ${{ secrets.PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            sudo su
            git config --global --add safe.directory /var/back-end/financial-board-server
            cd /var/back-end/financial-board-server

            # 파일 권한 확인 및 수정
            sudo chown -R $USER:$USER /var/back-end/financial-board-server
            sudo chmod -R 755 /var/back-end/financial-board-server

            # 로컬 변경 사항 스태시
            git stash

            git pull
            yarn
            yarn build

            # TypeORM 마이그레이션 실행
            yarn typeorm:run-master-data-migration:default

            yarn pm2 kill
            yarn pm2 start dist/main.js --name "backend-server"
