name: GITHUB Action

on:
  push:
    branches:
      - main

jobs:
  deploy-on-test:
    runs-on: ubuntu-latest

    steps:
      - name: 테스트
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # EC2의 주소
          username: ${{ secrets.USERNAME }} # EC2 접속 username
          key: ${{ secrets.PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          script: |
            sudo su
            cd /var/back-end/financial-board-server  # 여기 경로는 자신의 EC2에 맞는 경로로 재작성하기
            git pull 
            yarn 
            yarn build
            yarn typeorm:run-master-data-migration:default
            pm2 kill
            pm2 start dist/main.js --name "backend-server"
